version: '3.8'
services:
  db:
    build:
      context: ./database
      dockerfile: Dockerfile
    volumes:
      - ./database/data/:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 81:8080
    depends_on:
      - db

  rabbitmq:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    restart: always
    ports:
      - 15672:15672
      - 5672:5672

  consumer:
    build:
      context: ./consumer-service
      dockerfile: Dockerfile
    environment:
      - MQ_URL=amqp://rabbitmq
      - QUEUE_NAME=my-queue
    depends_on:
      - rabbitmq
      
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - MYSQL_HOST=db
      - MQ_URL=amqp://rabbitmq
      
      - DEBUG=backend:*
      - MYSQL_DB=sword_health_tasks
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=root
      - ENCRYPTION_KEY=P1bqV8JEQq9FP97B9IEGY93daKcDYAzKp33VDEU+Qfc=
      - QUEUE_NAME=my-queue
    ports:
      - 3000:3000
    depends_on:
      - db
      - rabbitmq